Module.register("facts",{

	// edit these
	defaults: {
		updateInterval: 30,		// how long a fact stays up in seconds
		fadeSpeed: 2,			// fade out of text in seconds
		category: 'random',		// pick a category below, or use 'random'
		facts: { 
			animals: [
				"It is illegal to hunt camels in Arizona without a permit.",
				"Opossums don't play dead - they pass out from fear.",
				"The average horse outputs approximately 15 horsepower.",
				"Snakes can predict earthquakes.",
				"Leeches were used to predict the weather.",
				"Pigeons can't fart.",
				"A snail has 2,500 teeth.",
				"Two-thirds of a cat’s life is spent asleep",
				"A giraffe only needs 1.9 hours of sleep a day, whereas a brown bat needs 19.9 hours a day",
				"Elephants sleep less than any other animal.",
				"Humans usually have between four to six dreams a night.",
				"The Giant Squid has the largest eyes of all animals",
				"The record for most egg yolks in one egg is 9 yolks.",
				"The largest chicken egg ever recorded weighed 12 ounces and contained two yolks.",
				"Grapes and raisins, as well as onions, garlic, and chives, are all extremely harmful foods for cats.",
				"Cats have up to 100 different vocalizations — dogs only have 10.",
				"If your cat approaches you with a straight, almost vibrating tail, this means that he is extremely happy to see you.",
				"Certain cats go crazy for foods you wouldn’t expect, like olives and potato chips.",
				"In Celtic and Norse mythology, roosters are messengers of the underworld.",
				"A small child could swim through the veins of a blue whale.",
				"The first cow in America arrived in 1611.",
				"Today, one cow can produce the milk that it once took 10 cows to produce.",
				"Armadillos are bulletproof.",				"Birds can sleep with one eye open.",
				"The first hot air balloon passengers were a sheep, duck, and rooster.",
				"Elephants can smell water from miles away.",
				"The average dog can understand over 150 words.",
				"The flamingo can only eat when its head is upside down.",
				"Elephants are afraid of bees.",
				"Lobsters pee from their faces.",
				"Fleas can jump around 130 times their own height.",
				"If chickens listen to classical music, they can lay bigger and heavier eggs.",
				"Mother hens talk to their chicks while they’re still in the eggs, and the chicks can chirp back while in the shell.",
				"Chickens have three eyelids.",
				"Mother hens teach their chicks what to eat and what to avoid.",
				"Cats dream, just like people do.",
				"Cats were first brought to the Americas in colonial times to get rid of rodents.",
				"There have been studies that show that goats, like us, have accents.",
				"There are 700 million feral cats live in the United States.",
				"The Labrador Retriever has been on the top 10 most popular breed list for longer than any other.",
				"Forty-five percent of U.S. dogs sleep on their owner's beds.",
				"All dogs dream, but puppies and old dogs dream more than adult dogs.",
				"70% of people sign their dog's name on their holiday cards.",
				"Dogs' noses can sense heat, so even blind or deaf dogs can hunt",
				"A human yawn can trigger a yawn in a dog.",
				"The Australian Shepherd is from America, not Australia.",
				"Human blood pressure goes down when petting a dog.",
				"There are over 75 million pet dogs in the U.S.",
				"Dogs are not color-blind. They can see blue and yellow.",
				"All puppies are born deaf.",
				"Dalmations are born white. They get spots as they get older.",
				"Dogs have less taste buds than humans.",
				"A bloodhound's sense of smell is so accurate that it can be used in court.",
				"30% of all households have a dog.",
				"Dogs evolved from an extinct type of wolf.",
				"Dogs can learn over 100 words and gestures.",
				"Dogs only sweat from their paws.",
				"Dogs are as smart as a two year old.",
				"Dachshunds were bred to fight badgers",
				"Bluey is the oldest dog to ever live. 29 years 5 months.",
				"Dogs can detect cancer and other diseases in humans.",
				"Three dogs survived the sinking of the Titanic.",
				"There are more than 150 dog breeds.",
				"The most popular name for a dog is Max",
				"Former US President Teddy Roosevelt had a Pit Bull named Pete.",
				"An adult dog has 42 teeth.",
				"The top 5 US dog breeds are Labrador Retriever, Golden Retriever, German Shepherd, Beagle, and Dachshund.",
				"House cats are 95.6% tiger",
				"Cats are believed to be the only mammals who don’t taste sweetness.",
				"Cats are supposed to have 18 toes",
				"Cats can jump up to six times their length.",
				"Cats’ claws all curve downward, which means that they can’t climb down trees head-first.",
				"Cats have 230 bones, while humans only have 206.",
				"Cats walk like camels and giraffes: They move both of their right feet first, then move both of their left feet",
				"Cats typically sleep for 12 to 16 hours a day.",
				"Cats are crepuscular, which means that they’re most active at dawn and dusk.",
				"Cats can spend up to a third of their waking hours grooming.",
				"Pigs are considered the 4th most intelligent animal",
				"People who take care of chickens are chicken tenders",
				"Golden Wyandottes lay about 200 Eggs a year",
				"Golden Wyandottes were first bred in the late 1880s",
				"Golden Wyandottes weigh about 6lb for hens and up to 8½lb for roosters",
				"Golden Wyandotte eggs are a cream to light brown color and large in size",
				"Golden Wyandottes were created in Wisconsin by mixing Silver Laced Wyandottes with a Partridge, Brown Leghorn and Cochin.",
				"Golden Comet chicken is a breed hybrid also known as Golden Buff, Red Star, Cinnamon Queen, and Gold Sex-Link",
				"Golden Comets lay 250–320 eggs per year",
				"Golden Comet hens weigh an average of 4 pounds",
				"Cinnamon Queens are a mix between Rhode Island Red roosters and Silver Laced Wyandotte hens",
				"Cinnamon Chickens lay approximately 260 eggs/year",
				"Cinnamon Queens live up to 10 years",
				"Lavender Orpington hens lay 170-200 eggs a year.",
				"Lavender Orpingtons live 8-10 years.",
				"The first Orpington chickens were bred by William Cook in the 1800s",
				"The original Orpington was black-colored.",
				"Lavender Orpingtons were created in the late 1990s",
				"The original Black Orpington was bred by crossing Minorcas, Langshans and Plymouth Rocks",
				"Cochin comes from very large feather-legged chickens brought from China in the 1840s and 1850s",
				"The Cochin was included in the Standard of Excellence of the American Poultry Association in 1874",
				"The Wyandotte was created in the United States in the 1870s by four people",
				"Ameraucana chickens lay 150-200 eggs a year",
				"Ameraucanas live 7-8 years",
				"Ameraucanas come from Chilean Araucanas mixed with LOTS of other breeds",
				"An Elk's antlers are made of bone, and weigh as much as 40 pounds",
				"The Shawnee Indian name for Elk is Wapiti, which means white rump.",
				"Male Elk bathe in their own pee to attract females",
				"Elk weigh up to 700 pounds and can run 40 mph",
				"Male Elk are called bulls",
				"Male Elk lose their antlers every march, but grow them back by May",
				"Elk are very good swimmers",
				"Male Bison are up to 6 ft tall and 11 ft long",
				"Wild Bison live up to 25 years",
				"Both male and female Bison grow horns",
				"30-60 million bison lived in North America until the mid 1800s",
				"Bison run faster than horses",
				"The Sailfish is the fastest water animal",
				"A Lobster has 10 legs",
				"Penguins are birds that cannot fly, but can dive up to 500 feet.",
				"Deer can jump eight feet high.",
				"The rooster is the national animal of France.",
				"There's an island in South Carolina where only monkeys are allowed.",
				"Most roosters can crow by the time they are four months old.",
				"When a rooster finds food, he calls the other chickens over to eat first.",
				"Rooster Spurs Continuously Grow throughout their lives",
				"Roosters make sure their hens eat before they do.",
				"A rooster protects his flock and will warn the other chickens if he senses danger.",
				"If there is no rooster in a flock, a hen will step up to take charge.",
				"Porcupines can float.",
				"Owls can’t move their eyeballs!",
				"Elephants are the only animals that can’t jump!",
				"Rats can have as many as 20 babies at a time.",
				"Rats make sounds similar to laughter when they are happy.",
				"A rat can fall as far as 50 feet without being injured.",
				"A group of rats is called a mischief.",
				"Rats teeth never stop growing.",
				"Rats are very clean animals - even cleaner than cats!",
				"Rats take care of injured and sick members of their group.",
				"Rats learn what food that they like from smelling the breath of other rats.",
				"A cat has 32 muscles in each ear, humans only have 6.",
				"Cats spend 15-20% of their time grooming.",
				"Dogs only sweat from the bottoms of their feet.",
				"A pack of kittens is called a kindle.",
				"To survive, every bird must eat at least half its own weight in food each day.",
				"A bird's heart beats 400 times per minute.",
				"Many hamsters only blink one eye at a time.",
				"Iguanas are able to hold their breath for up to 30 minutes.",
				"A garter snake can give birth to 85 babies.",
				"The oldest pet goldfish lived to 43.",
				"Rabbit teeth never stop growing.",
				"Chickens are living descendants of dinosaurs.",
				"Chickens have better colour vision than humans.",
				"Chickens have over 30 unique vocalizations that they use to communicate.",
				"Chickens are able to recognize over 100 different faces.",
				"Chickens bathe by covering themselves in dirt.",
				"Egg shell colour can be determined by the hen’s earlobe.",
				"Chickens dream when the sleep.",
				"Chickens can run at 9MPH.",
				"Chickens do not sweat.",
				"There are more chickens than humans in the world.",
				"All 'cows' are female. Males are called bulls or steer.",
				"Cows can see almost 360 degrees.",
				"Goats were one of the first animals to be domesticated, and they are raised for their wool, milk, and meat.",
				"It takes a sloth a month to digest one leaf.",
				"Hedgehogs have 5000 - 7000 spines on their back.",
				"Giant anteater tongues are 2 feet long!",
				"A female peacock is called a peahen.",
				"Anteaters don't have teeth, but eat 35,000 ants and termites each day.",
				"Hummingbirds can fly upside down.",
				"A group of bats is called a cauldron.",
				"A group of caterpillars is called an army.",
				"A group of crows is called a murder.",
				"A group of elephants is called a parade.",
				"A group of ferrets is called a business.",
				"A group of frogs is called an army.",
				"A group of giraffes is called a tower.",
				"A group of hyenas is called a cackle.",
				"A group of jellyfish is called a smack.",
				"A group of jaguars is called a shadow.",
				"A group of kangaroos is called a mob.",
				"A group of lemurs is called a conspiracy.",
				"A group porcupines is called a prickle.",
				"A group of rhinos is called a crash.",
				"A group of gerbils is called a horde.",
				"A group of hippos is called a bloat.",
				"An average blue whale weighs as much as 3 - 4 elephants.",
				"A Blue Whale's tongue weighs as much as an elephant.",
				"At birth, a panda is smaller than a mouse.",
				"A narwhal's tusk is actually a tooth!",
				"Reindeer's eyes change color from gold in the summer to blue in the winter.",
				"Giraffe tongue is black.",
				"Kangaroos can jump 30 feet.",
				"Only male turkeys gobble.",
				"Beavers were once the size of bears.",
				"Termites eat through wood 2 times faster when listening to rock music.",
				"The bullfrog is the only animal that never sleeps.",
				"Turtles can breathe out of their butts.",
				"Elephants are capable of swimming 20 miles a day.",
				"Sloths can hold their breath longer than dolphins can.",
				"When a koala is born, it is about the size of a jelly bean.",
				"A caterpillar has more muscles than a human.",
				"Some cats are allergic to humans.",
				"Ants won’t cross a chalk line.",
				"Baby bunnies are called kittens.",
				"Gentoo penguins propose to their life mates with a pebble.",
				"A group of porcupines is called a prickle.",
				"In Arizona, it's illegal for donkeys to sleep in bathtubs.",
				"The very first animals in space were fruit flies.",
				"Sloths don't fart.",
				"Naked Mole Rats have incisors that can move independently of each other, a bit like chopsticks.",
				"Naked Mole Rats can live for up to 30 years, making them the longest-living rodents.",
				"A type of stick insect called Chan’s Megastick can grow to 1.5 feet long!",
				"A platypus is a mammal that lays eggs!",
				"Pufferfish teeth grow continuously.",
				"Grizzly bears can run up to 30 miles an hour!",
				"Scorpions can be found on every continent except Antarctica!",
				"Lizards use their tongue to smell!",
				"Earthworms have 5 hearts.",
				"Kangaroos can’t fart.",
				"Giraffes hum to each other at night.",
				"You can tell the temperature by counting a cricket's chirps.",
				"Some Salamanders can regrow their tails, legs, and parts of their eyes!",
				"A male Ostrich can roar like a Lion.",
				"A crocodile can't stick it's tongue out.",
				"Cats can't taste anything sweet.",
				"A blue whale's heart can weigh up to 400 lbs.",
				"A beefalo is real animal that's part cow, part bison.",
				"A grizzly bear can run as fast as a horse.",
				"Anteaters have no teeth.",
				"The Goliath frog from Western Africa can grow up to 16 inches long and weigh 7 lbs.",
				"The unicorn is the national animal of Scotland.",
				"There are more tigers in Texas than the rest of the world.",
				"Mammoths went extinct 1,000 years after the Egyptians finished building the Great Pyramid.",
				"Cats were domesticated 10,000 - 12,000 years ago",
				"Dogs were domesticated over 30,000 years ago",
				"Horses were domesticated 20,000 years ago",
				"Cows were domesticated 10,000 years ago",
				"Chickens were domesticated 7000 years ago",
				"Goats were domesticated 10,000 years ago",
				"Sheep were domesticated 10,000 years ago",
				"Pigs were domesticated 8500 years ago",
				"Some fish cough to clear particles and bacteria out of their gills.",
				"Sharks don't have any bones in their bodies.",
				"Sea sponges are considered the least evolutionarily advanced animal on the planet.",
				"There are 6 to 10 million different species of insects!",
				"Deer will flash the white underside of their tail to warn others of danger.",
				"Dolphins only shut half their brain off while sleeping.",
				"Elephants are the only animal that can't jump.",
				"Most groups of penguins actually live in warm climates.",
				"Panthers are actually leopards or jaguars with a black color mutation.",
				"Slugs have four noses",
				"Caterpillars have 12 eyes.",
				"There are more than 1,000 kinds of bats in the world.",
				"A hippopotamus runs faster than people",
				"Kangaroos can't walk backward.",
				"Dogs' hearing is 10 times better than a human's",
				"Dogs can smell 100,000 times better than humans.",
				"A group of frogs is called an army.",
				"A pet hamster can run up to 8 miles a night on a wheel.",
				"Monkeys can go bald in old age, just like humans.",
				"Frogs can drink water through their skin.",
				"Only male toads croak.",
				"Owls can't move their eyeballs.",
				"A shrimp's heart is in their head.",
				"Hummingbirds can fly backwards.",
				"A tiger's skin is striped like it's fur.",
				"Gorillas burp when they are happy.",
				"Hippo's produce pink milk.",
				"A hippo's lips are nearly two feet wide!",
				"Australia has over 750 different species of reptile.",
				"There are over 470 million dogs in the world. That’s 1 dog for every 16 people!",
				"An ostrich’s eyes are bigger than its brain.",
				"Bats are the only mammals that can fly.",
				"Some hummingbirds weigh less than a penny.",
				"Dragonflies can see in all directions at the same time.",
				"A giraffe has seven bones in its neck.",
				"Sharks lay the biggest eggs in the world.",
				"Cheetahs only need to drink once every three to four days.",
				"Giant anteaters can eat over 30,000 insects a day.",
				"Starfish have no brain and no blood. And they aren’t even fish!",
				"Baby elephants are able to stand within 20 minutes of being born.",
				"Reindeer grow new antlers every year.",
				"Sloths are so slow that in their native climate, algae actually grows on their fur.",
				"New Zealand has more sheep than people.",
				"A grizzly bear’s bite is so strong that it can crush a bowling ball.",
				"Rats laugh when being tickled.",
				"There are no male or female earthworms.",
				"A jaguar’s night vision is six times better than a human’s.",
				"A hummingbird’s wings can beat up to 200 times per second.",
				"Humans share 98.8% of chimpanzee DNA.",
				"A rhinoceros horn is made from compacted hair.",
				"A chameleon’s tongue is as long as its body.",
				"Adult bison are the largest land mammals in North America.",
				"Nine-banded armadillos always give birth to identical quadruplets.",
				"The giant tortoise of the Galapagos Islands weighs as much as a brown bear.",
				"Sea otters have the densest fur of any mammal.",
				"An emperor penguin can stay underwater for 27 minutes.",
				"Both male and female pigeons produce milk for their babies.",
				"Camels can drink 50 gallons of water in one minute.",
				"Blue whales make the loudest sound of any animal and an be heard 500 miles away.",
				"A group of flamingos is called a flamboyance.",
				"Sheep have four stomachs.",
				"Only female mosquitos bite.",
				"Dogs are not colorblind, but they can’t see red. Dog vision only includes shades of yellow and blue.",
				"Cats can rotate their ears 180 degrees—from pointing directly forward to all the way back.",
				"The chicken is the closest living relative to the T-Rex.",
				"Cows have best friends, and they get stressed when they are separated.",
				"Some chickens lay eggs that are green or even blue!",
				"Pigs are one of the most intelligent non-human animals (after chimpanzees, dolphins, and elephants).",
				"Octopuses have nine brains.",
				"Male seahorses are the ones who are pregnant and give birth, not the females.",
				"Sea otters hold hands while they sleep so they don’t drift apart."	,
				"Jellyfish have no brain, heart, bones, or eyes, and they’ve been around since before the dinosaurs.",
				"Baby elephants use their trunks the same way that baby humans use a pacifier.",
				"Female lions do about 90% of the hunting.",
				"Almost two-thirds of the bears in the world live in North America.",
				"Butterflies taste with their feet.",
				"Snails can sleep for three years at a time.",
				"Many species of bugs fart, but their farts are so tiny we can’t smell them.",
				"Some bats can eat up to 1,000 insects in an hour.",
				"Just like humans, bats have belly buttons.",
				"The ears of an African Elephant can be 6 feet long!",
				"Honey bees can fly at speeds of up to 15 miles per hour.",
				"Mosquitoes can smell which blood type you are.",
				"Sloths have more neck bones than giraffes",
				"Cats have fewer toes on their back paws",
				"All worker bees are female",
				"The Greenland Shark can live for around 500 years.",
			],
			art: [
				"Purple is the color for epilepsy awareness because of its association with lavender, which is a traditional herbal treatment for the disease.",
				"Vincent Van Gogh painted The Starry Night during his stay at a psychiatric facility.",
				"Research has shown practicing art correlates with higher achievement in reading and maths.",
			],
			conversation: [
				"Do you like dinner or breakfast foods better?",
				"What’s your favorite holiday?",
				"What’s the funniest joke you know?",
				"What three things would you bring with you to a deserted island?",
				"What's your favorite movie?",
				"Would you rather be able to slide down rainbows or jump on clouds?",
				"Would you rather be super strong or super fast?",
				"Would you rather be able to talk to animals or read people's minds?",
				"Would you rather drink everything with your ears or eat everything with your belly button?",
				"Would you rather be able to control fire or water?",
				"Would you rather fly to space or visit every country?",
				"Would you rather have wings or a mermaid tail?",
				"Would you rather live in an amusement park or a zoo?",
				"Would you rather blow fire or shoot ice balls?",
				"Would you rather be all alone in the desert or in the jungle?",
				"Would you rather have the chance to design a new toy or create a new TV show?",
				"Would you rather live in a cave or a treehouse?",
				"Would you rather ride on a rollercoaster or on a water slide?",
				"Would you rather drive a race car or fly a helicopter?",
				"Would you rather look like a skunk or smell like a skunk?",
				"Would you rather have cotton candy hair or popcorn hair?",
				"Would you rather have a personal maid or a personal chef?",					"What's the last new skill you learned?",
				"Are you a cat or dog person?",
				"Do you have a secret talent?",
				"What's something you'd love to be an expert at?",
				"If you were an animal, which one do you think you'd be?",
				"How many animal noises can you make?",
				"What's your favorite smell?",
				"What would you do with a million dollars?",
				"What's the coolest thing you've ever seen?",
				"What would you do if you had no TV?",
				"What is the best surprise you ever had?",
				"What is the most interesting dream you've ever had?",
				"If you could go anywhere in the world, where would you go?",
				"If you could have one superpower, what would it be?",
				"What's the worst super power?",
				"What do you usually play at recess?",
				"What's your favorite holiday?",
				"What school rule do you wish you could get rid of?",
				"What's the best part about being a kid?",
				"If you could only eat one food for the rest of your life, what would it be?",
				"If you were a parent, what rules would you have?",
				"Who's the nicest person you know?",
				"What's the nicest thing anyone has ever said to you?",
				"What's the funniest joke you know?",
				"If you could only see one color, which one would you choose?",
				"What do you like most about your mom?",
				"If you could live in a cartoon, what cartoon would you choose?",
				"If you could change the color of the sky, what color would you choose?",
				"If your pets could talk, what would they say?",
				"If you wrote a book, what would it be about?",
				"What color do you think is the happiest?",
				"What is the best ice cream flavor?",
				"Which animal is the best of all?",
			],
			culture: [
				"Japan has 23 vending machines per person.",
				"Scotland has 421 words for snow",
				"Chinese students have 14 hours of homework per week.",
				"Schools in Canada teach in both French and English.",
				"French students have the shortest school year and the longest school day.",
				"Each year of schooling increases your earnings by up to 10%",
				"The Shishi High School in China was built in 194 AD.",
				"Meal-time is considered a class in France.",
				"Students in South Korea must stay and help clean the classroom after class.",
				"In Bangladesh, there are 100 schools on boats.",
				"In Colombia, some kids travel to school on a zipline.",
				"A school in Germany is built to look like a giant white cat.",
				"Schools in Japan don't have janitors because students do the cleaning.",
				"85% of jobs require some college.",
				"One school in India has more than 32,000 students.",
				"The smallest school in the world has one student and one teacher.",
				"Schools in Brazil close at noon so students can have lunch with their parents",
				"In South Korea, there are more fried chicken restaurants than there are McDonald’s restaurants worldwide.",
			],
			food: [
				"A janitor invented the flaming hot Cheetos.",
				"McDonald’s once had bubblegum flavored broccoli.",
				"Pineapples are named after pinecones.",
				"Cap'n Crunch's full name is Horatio Magellan Crunch.",
				"75 burgers are sold in McDonald’s every second.",
				"Tiramisu translates to ‘take me to heaven’ in Italian.",
				"Buttermilk does not contain any butter.",
				"Coffee was originally chewed",
				"The average American spends $2000 each year on coffee.",
				"Finland's citizens drink more coffee than any other country in the world.",
				"There's a Starbucks at CIA headquarters.",
				"Coffee dates back to 800 AD.",
				"Coffee beans are seeds.",
				"Brazil grows the most coffee in the world.",
				"Only two US states produce coffee. California and Hawaii.",
				"The most expensive coffee costs more than $600 per pound",
				"The word coffee comes from the Arabic word for 'wine'",
				"Coffee beans are green when they're picked.",
				"The first coffee house opened in Turkey in 1475.",
				"All tea comes from the same plant.",
				"Tea is the most consumed beverage in the world aside from water.",
				"It takes 2000 tea leaves to make one pound of tea.",
				"In the 1600s, scientists thought tea was bad for you.",
				"Some cultures add butter to their tea.",
				"Green tea has been associated with weight loss.",
				"A tea tree can grow up to 52 feet high.",
				"Lemons float, but limes sink",
				"German chocolate cake was invented in Texas",
				"The average strawberry has 200 seeds.",
				"You can buy a square watermelon in Japan.",
				"The average age of an American farmer is 58.",
				"Over 92% of land in Nebraska is farmland.",
				"South Dakota farmers grow 975 million pounds of sunflowers.",
				"Texas has the most farms in the US.",
				"Most farmers' markets source products within 50 miles.",
				"A little baking soda can help you grow sweeter tomatoes.",
				"Vanilla beans come from a variety of orchid.",
				"Tomato fruits were considered poisonous by Europeans and didn’t become popular until the pizza was invented",
				"There are more than 80,000 species of edible plants on the Earth",
				"A cluster of bananas is called a hand.",
				"Cranberries float because of a small air pocket inside.",
				"Apples float because they’re composed of 25% air.",
				"The first potatoes were cultivated in Peru about 7,000 years ago.",
				"The average strawberry has 200 seeds.",
				"Ginkgo biloba is one of the oldest living tree species, and dates back about 250 million years.",
				"Banana “trees” are actually herbs.",
				"A lemon contains more sugar than a strawberry.",
				"Asparagus can grow up to 7 inches in a day.",
				"There are over 2,500 apple varieties grown in the U.S.",
				"The first candy canes had no stripes.",
				"Both green and black tea come from leaves of the same tree.",
				"The world's longest French fry is 34 inches long.",
				"Ice cream was once called 'cream ice'.",
				"Almonds are members of the peach family.",
				"Ripe cranberries can bounce like a ball.",
				"Peanuts are not nuts. They grow in the ground, so they are legumes.",
				"Honey does not spoil, due to low moisture content.",
				"Strawberries are not berries, but bananas and avocados are.",
				"Cucumbers are 95% water.",
				"Rotten eggs float.",
				"It takes about 50 licks to finish one scoop of ice cream.",
				"Apples are actually part of the rose family.",
				"It takes 2-3 years to grow a pineapple to full size.",
				"Strawberry is the only fruit with seeds on the outside.",
				"Ketchup used to be sold as medicine for indigestion.",
				"The world's heaviest carrot was 22 lbs. As much as Ethan at 6 months old.",
				"French fries originated in Belgium.",
				"Baby Carrots were invented in 1986.",
				"Coconuts kill more people than sharks every year.",
				"A strawberry isn't a berry but a banana is.",
				"The earth has over 80,000 species of edible plants. We only eat about 30.",
				"Avocados and watermelons are berries.",
				"Ancient Romans thought strawberries could cure bad breath.",
				"Strawberries taste sweeter at room temperature.",
				"Blueberries are one of the only natural foods that are truly blue in color.",
				"Maine produces more wild blueberries than anywhere else in the world.",
				"Small pockets of air inside cranberries cause them to bounce and float in water.",
				"The pod of an orchid provides us with vanilla flavouring.",
				"Commercial egg farms produce more than 65 billion eggs each year.",
				"Roughly two-thirds of mushrooms grown in the U.S. come from Pennsylvania.",
				"US peanut farmers produce 3 million tons of peanuts each year.",
				"The average person eats 61 pounds of beef per year.",
				"To make one pound of honey, a honeybee must touch two million flowers.",
			],
			gaming: [
				"Super Mario Land was the most popular game on the Game Boy during its release.",
				"There are over 40 million games in Roblox",
				"The Kleus Aphthiton is the rarest hat in Roblox",
				"In 2021, Roblox paid out over $500 million to Roblox creators",
				"Roblox used to be called Dynabricks",
				"The idea of creating the Xbox began in 1998.",
				"65% of US adults love playing video games.",
				"In 2020, 41% of gamers were women.",
				"58 million Xbox One's have been sold",
				"Over 155 million Playstation 2's have been sold",
				"154 million Nintendo DS's have been sold",
				"139 million Nintendo Switches have been sold",
				"117 million Playstation 4's have been sold",
				"102 million Playstations have been sold",
				"101 million Nintendo Wii's have been sold",
				"87 million Playstation 3's have been sold",
				"84 million XBox 360s have been sold",
				"Nintendo started as a card game company in 1889.",
				"Fortnite has more users than Netflix.",
				"Fortnite made $2.4 billion in 2018.",
				"Minecraft is the biggest selling video game of all time! It has sold 238,000,000 copies.",
				"The rarest item in Minecraft is the Dragon Egg.",
				"Minecraft was originally called 'Cave Game'.",
				"Sonic's full name is Sonic Maurice the Hedgehog.",
				"Sonic was originally going to be a rabbit.",
			],
			geography: [
				"There is a city in Oregon called Boring.",
				"Tokyo is the capital of Japan",
				"Alaska is the largest state in America",
				"The capital of South Korea is Seoul",
				"The capital of Spain is Madrid",
				"The Arctic Ocean is the smallest ocean",
				"There are 7 continents in the world",
				"The Earth’s longest mountain range is underwater! It is 50,000 miles long",
				"The biggest pyramid on earth is not in Egypt, but in Mexico.",
				"The Nile River in Egypt is 4,135 miles long.",
				"Maine is the closest U.S. state to Africa.",
				"Maine is the only state that only borders one state",
				"Alaska has the longest coast in the US, 6640 miles!",
				"The highest mountain in the US is Mount Denali at 20310 ft in Alaska",
				"The longest river in the US is Missouri River at 2341 miles.",
				"Lake Superior is the largest freshwater lake in the world",
				"The highest waterfall in the US is Colonial Creek Falls at 2568  ft in Washington state.",
				"Asia is the largest continent in the world.",
				"The Grand Canyon is the largest canyon in the world. 2600 feet high and 277 miles long.",
				"Russia is just 2 miles from Alaska!",
				"Hawaii's Mauna Loa is the largest active volcano in the world.",
				"The Andes in South America are the longest mountain range in the world.",
				"Antarctica is home to the largest desert in the world.",
				"Iron makes up around 5% of the earth's crust.",
			],
			health: [
				"Losing weight alters brain activity.",
				"There is enough iron in your body to make a 3-inch nail.",
				"There are no muscles in your fingers: Their function is controlled by muscles in your palms and arms.",
				"On average, a 150-pound person burns 114 calories per hour while standing and doing nothing.",
				"The average person spends more time on the toilet than they do exercising.",
				"Your height differs depending on the time of day.",
				"Hyponatremia occurs when you overdose on water.",
				"Humans have unique tongue prints.",
				"Fingernails grow four times faster than toenails.",
				"Your nose and ears continue growing for your entire life.",
				"Your heart is the same size as your fist.",
				"Every step uses 200 different muscles",
				"An average yawn lasts 6 seconds.",
				"The only muscle that never tires is the heart.",
				"The human foot has 26 bones.",
				"The tongue is the fastest healing part of a human body.",
			],
			history: [
				"The current American flag was designed by a high school student",
				"The inventor of the microwave appliance received only $2 for his discovery",
				"The Great Wall of China is over 13,000 miles long.",
				"The Great Wall of China is over 2,300 years old and is 13,170 miles long.",
				"The Eiffel Tower in Paris, France, was is 1,063 feet tall.",
				"The Statue of Liberty in New York City was a gift from France and is 151 feet tall.",
				"The Statue of Liberty holds the torch in the right hand.",
				"Alexander Graham Bell invented the telephone",
				"Ancient Egyptions built their homes using mud bricks",
				"China was the first country to use paper money",
				"An empire is a group of countries of peopples ruled by one government",
				"The Sumerians invented the wheel and sailboat to trade items to and from Sumer",
				"The British Empire was the largest empire in world history",
				"The first stroller was engineered to be pulled by a goat",
				"Bananas glow blue under black lights",
				"Algebra was created by Arab-Mohammed ibn-Musa al-Khowarizmi in 825AD",
				"Ancient Egyptians used complex forms of math in 3000 BC.",
				"Geography is the study of the surface of the earth",
				"An artifact is something that was made by man and left behind",
				"An archaeologist is someone who studies the artifacts of the past.",
				"An anthropologist is someone who studies the cultures of the past.",
				"Culture is a way of life, idea, customs, and skills of a group that are passed through generations",
				"Civilization is a society that has cities, organized government, and workers wiith specialized job skills",
				"Our current calendar was designed in 500 AD to highlight the birth of Christ",
				"Early civilizations developed near water which provided food, water, transportation, trade, and irrigation",
				"Chicago is named after smelly garlic that once grew in the area.",
				"Instead of saying 'Cheese!' people used to say 'Prunes!' when having their pictures taken.",
				"The Vikings discovered America, not Christopher Columbus.",
				"The Statue of Liberty used to be a lighthouse.",
				"Cleopatra, Queen of Egypt, came to power at 12 years old!",
				"President Abraham Lincoln was once a wrestling champion.",
				"New York was once named New Amsterdam",
				"Native Americans settled in North America in about 15000 BC",
				"The US is the only country in the world that has all five climate zones on earth!",
				"Delaware was the first state to join the US.",
				"Hawaii was the last state to join the US.",
				"Pepsi, the soft drink company, once became the 6th largest military in the world after the Soviets exchanged 17 submarines, one frigate, one cruiser, and one destroyer for three billion dollars worth of Pepsi.",
				"The shortest war fought between Britain and Zanzibar, lasted 38 minutes and ended with a British victory.",
				"Nobody knows who invented the fire hydrant because the patent was lost in a fire.",
				"Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.",
				"The wheel was invented in 3500 BC by the Sumerians (Iraq)",
				"Johannes Gutenberg invented the printing press sometime between 1440 and 1450",
				"Alexander Fleming discovered penicillin in 1928",
				"The ompass was invented in China  between the 100 B.C. and 100 A.D",
				"Alexander Graham Bell was the first to be awarded a patent for the telephone on March 7, 1876",
				"Fire has been used by humans as early as 1.5 million to 2 million years ago",
				"Egyptians used concrete in their buildings in 3000 B.C",
				"Roger Bacon first developed the magnifying glass in 1268",
				"Alessandro Volta invented the first battery in 1800",
				"The X-Ray was invented in 1895",
				"Agriculture was invented 12,000 years ago",
				"Human language was invented 150,000 to 200,000 years ago",
				"Sliced bread was invented in 1928",
				"The first plough was used in 500BC in China",
				"Paper was invented in China in 105 AD",
				"The microscope was invented in 1590",
				"The electric guitar was invented in 1931",
				"The ukelele was invented in 1879",
				"The piano was invented by Bartolomeo Cristofori in 1700",
				"The zipper was invented in 1893",
				"The first gaming console, Magnavox Odyssey, was invented in 1972",
				"Soap was invented in 2800BC by Babylonians",
				"Easter Island has 887 giant head statues",
				"The first firefighters were in 200 AD",
				"A 10 year old found a 10,000 year old arrowhead in New Jersey",
				"The first schools were 2070 BC-1600 BC in China",
				"China was the first to use paper money in the 800 AD",
				"The first sailboats were invented in 6000 BC",
				"There are about 4000 religions in the world",
				"The telescope was invented in 1608 in the Netherlands",
				"The first automatic washing machine was invented in 1937",
				"The first pair of shoes were invented in 7000-8000 BC",
				"The oldest drawing is in Indonesia, from 45,500 years ago",
				"The modern pencil was invented in 1795",
				"The colored pencil was invented in 1834",
				"Mirrors were invented 8000 years ago in Turkey",
				"Forks were first used around 2400–1900 BC",
				"The fire extinguisher was invented in 1723",
				"The flashlight was invented in 1899",
				"The internet was invented by the US government in the 1960s",
				"Abraham Lincoln stored notes in his top hat",
				"The Eiffel Tower was created for Barcelona but was too ugly",
				"The University of Oxford is older than the Aztec Empire",
				"Before toilet paper was invented, Americans used to use corn cobs.",
				"The Statue of Liberty used to be a lighthouse.",
				"The last letter added to the alphabet was actually 'J.'",
				"No one was burned at the stake during the Salem witch trials.",
				"People used food sacks as clothing during the Great Depression.",
				"It was once believed that redheads became vampires after death.",
				"Tablecloths were originally used as a napkin for everyone at the table.",
				"The first car was actually invented in Europe, not America",
				"The Great Pyramid of Giza was the tallest man-made structure for over 3,800 years.",
				"Colosseum in Rome could hold an estimated 50,000 to 80,000 spectators",
				"The printing press was invented by Johannes Gutenberg in 1439.",
				"World War I was a global war that took place from 1914 to 1918.",
				"World War II was the deadliest conflict in human history, from 1939 to 1945 and involving over 30 countries.",
				"The wheel was invented in ancient Mesopotamia around 3500 BC.",
				"The Industrial Revolution was a period of major industrialization that took place during the late 1700s and early 1800s",
				"The Beatles were an English rock band formed in Liverpool in 1960.",
				"Alexander Graham Bell is often credited with being the inventor of the telephone in the 1870s",
				"Hieroglyphs were a system of writing used by the ancient Egyptians.",
				"The Suez Canal is a man-made sea-level waterway in Egypt, connecting the Mediterranean Sea to the Red Sea",
				"The space age began with the launch of the Soviet satellite Sputnik 1 on October 4, 1957.",
				"The American civil rights movement was a fight for social justice for Black Americans, primarily occurring in the 1960s.",
				"The Silk Road was a network of trade routes connecting the East and West in ancient times.",
				"The first partially successful photograph was made in approximately 1816 by Nicephore Niepce,",
				"The Battle of Waterloo in 1815 marked the final defeat of Napoleon Bonaparte.",
				"In 1963, Valentina Tereshkova became the first woman to travel to space.",
				"The first vending machine was created in Egypt around 215 BC.",
				"George Washington had to borrow money to get to New York City for his inauguration.",
				"The first vacuum cleaner was so large it was hauled by horses.",
				"The first calculator was invented in the 1600s. It could only add and subtract.",
				"The first alarm clock could only ring at 4 a.m.",
				"The fortune cookie was invented in San Francisco, not China.",
				"The first Valentine’s Day card was sent in the 15th century.",
				"The sandwich was named after the 4th Earl of Sandwich in the 1700s.",
				"The White House was burned down by the British in 1814 during the War of 1812.",
				"Elvis Presley auditioned for a gospel group and was told he couldn’t sing.",
				"Albert Einstein did not speak until age 4 and couldn’t read until 7.",
				"Vincent van Gogh only sold one painting in his lifetime, for about $50 in today’s money",
				"The Hundred Years’ War between England and France lasted 116 years, from 1337 to 1453.",
				"The Egyptians mummified over 70 million people",
				"The first public museum in the world opened in 1683",
				"Catherine the Great of Russia ordered the first smallpox vaccination in 1768",
				"It took about 15 years to build the Parthenon, the temple dedicated to the goddess Athena",
				"The Byzantine Empire finally fell in 1453 CE when Constantinople was conquered by the Ottoman Turks.",
				"The ancient Greek philosopher Socrates never wrote down any of his teachings.",
				"President Andrew Jackson had a pet parrot.",
				"Can you name the original 13 colonies?",
				"The american flag has had 27 versions.",
				"The US doesn't have an official language.",
				"President Madison was the shortest president at 5ft 4in and weighed barely over 100 pounds.",
				"President Van Buren was the first president to be born an American.",
				"Abraham Lincoln was 6 ft 4in, making him the tallest U.S. president.",
				"President John Tyler had 15 children.",
				"The ancient Egyptians invented paper, ink, pens, and toothpaste.",
				"Theodore Roosevelt was the first U.S. President to fly in an airplane.",
				"John F. Kennedy was the youngest person ever elected U.S. President at the age of 43.",
				"The shortest war in history was 38 minutes, between Britain and Zanzibar.",
				"The development of tools and the use of fire were key factors in the survival of early humans",
				"Cultural borrowing is the transfer of ideas or cuuustoms from one culture to another",
				"The most important event of the Old Stone Age was the discovery of fire.",
				"Agriculture is the cultivation of crops, which began in the New Stone Age.",
				"Historians consider the most important event of the New Stone Age to be the development of agriculture.", 
				"The places where the first civilizations developed are called the Cradles of Civilization.",
				"The earliest known civilization developed in Mesopotamia.",
				"Mesopotamia means 'land between the rivers.'",
				"Barter is a system of trade in which people exchange goods and services without money",
				"A  person skilled at making a particular product by hand is called an artisan",
				"A city-state is an independent state made up of a city and the land and villages surrounding it.",
				"King Nebuchadnezzar built the Hanging Gardens of Babylon for his wife.",
				"A line of rulers from the same family is called a dynasty.",
				"Egypt’s kings were called pharaohs.",
				"Re was the sun god, the main god of the Egyptians.",
				"A pyramid was a burial tomb for Egyptian pharaohs.",
				"The Dark Ages of ancient Greece (1100 B.C. to 750 B.C.) were a time of poverty due to war and earthquakes.",
				"A polis is a Greek city-state made up a city and the surrounding countryside.",
				"A hoplite was an ordinary citizen-soldier of the Greek army.",
				"A tyrant is someone who takes power for force and rules with total authority.",
				"An oligarchy is a government in which a few people hold the power to govern.",
				"A democracy is a government in which all citizens share in running the government.",
				"In Greece, Zeus was the main god worshiped",
				"In Greece, Athena was the goddess of widsom",
				"Myths are stories about gods and goddesses.",
				"The Age of Pericles was a period of great creativity and learning in ancient Athens.",
				"A tragedy is a play that tells a sad story in which people fail to overcome their difficulties.",
				"A fable is a short tale that teaches a lesson and usually involves animals.",
				"The tortoise and the hare is the most famous fable, and was written by a former slave.",
				"The Parthenon, in Greece, is a temple built to the Goddess Athena",
				"Socrates was the most famous Greek philosopher.",
				"Pythagoras was a philosopher who taught that everything in the universe could be explained in numbers.",
				"Hippocrates, 'the Father of Medicine' wrote a code of behavior for doctors",
				"A republic is a form of government in which the leader is elected by the citizens.",
				"Roman soldiers were called legionnaires",
				"The ancient Romans developed concrete.",
				"Romans used slaves, captured in war, to do their work.",
				"The favorite sport of the Romans was gladiator games.",
				"Israelites set up their kingdom in Canaan around 1000BC and believed it was promised to them by God.",
				"Monotheism is the belief in one god.",
				"The 3 branches of US Government are Legeslative, Executive, and Judicial",
				"Israelites recorded their history in the Hebrew Bible.",
				"The faith of the Israelites became known as Judaism.",
				"Because of a drought in Canaan, the Israelites moved to Egypt, where they were slaves.",
				"A mosque is a Muslim house of worship.",
				"Allah is the Arabic word for God.",
				"The holy book of Islam is called the Quran",
				"A subcontinent is a large landmass that is part of a continent but separate from it.",
				"A monsoon is a wind that blows one direction in summer and the opposite in winter.",
				"A guru is an Indian teacher",
				"Abraham Lincoln had four cats that lived in the White House with him.",
				"The Shang were the first rulers of China",
				"The Zhou dynasty ruled longer than any other in China.",
				"Confucius was ancient China's first great teacher and thinker",
				"The Great Wall was build across northern China to protect it from invaders.",
				"The Silk Road was a network of trade routes from western China to southwest Asia",
				"The Mayans built an empire in what is now southern Mexico",
				"The calendar of the Mayans had 365 days",
				"The Aztecs built an empire in what is now central Mexico",
				"The Inca built an empire in what is now Peru",
				"Machu Pichu waas a retreat for Incan kings",
				"The Middle Ages were a time period between ancient civilizations and modern times",
				"A warlord is a military ruler who runs a government.",
				"The Mongols lived in an area north of China",
				"Most of Africa rests on a plateau or an area of high, flat land",
				"The Berbers were the first known people to settle in North Africa",
				"Griots are African storytellers",
				"Many African villages were matrilineal, tracing their family through the mother.",
				"Samurai were Japenese warriors who pledged loyalty to nobles in return for land.",
				"A shogun is a military leader who commands the emporor's army.",
				"Calligraphy was handwriting used by the Japanese.",
				"The Franks were a Germanic people who settled in what is now France.",
				"Feudalism is a political system based on loyalty between lords and vassals",
				"Knights were warriors on horseback who fought for nobles in exchange for food.",
				"The Crusades were a series of wars between Christians and Muslims over control of the Holy land, lasting 200 years.",
				"Joan of Arc was a French peasant girl who led soldiers into battle; She was captured and burned.",
				"Humanism is a philosophy based on the idea that the individual and society are important.",
				"Christopher Columbus reached the Americas as he tried to sail to India",
				"Our current calendar was designed in 500 AD to highlight the birth of Christ.",
				"Prehistory is history that took place before development of writing",
				"Polytheism is the belief in many gods",
				"A pictograph is a picture that represents an object.",
				"A scribe is a person trained to write and keep records in ancient times.",
				"Egyptians believed their kings were both humans and gods.",
				"A Mummy is a body preserved by a special process.",
				"The laws of ancient Hebrews were called the Ten Commandments",
				"The Revolutionary War ended in 1783",
				"Shakespeare and Pocahontas both lived during the same time.",
				"The capital of the Hebrew lands was Jerusalem",
				"Tug-of-war was once an Olympic sport.",
				"The Declaration of Independence was signed on July 4, 1776",
				"The 1st president was George Washington (1789-1797)",
				"The 2nd president was John Adams (1797-1801)",
				"President John Adams was the author of the Massachusetts constitution.",
				"The 3rd president was Thomas Jefferson (1801-1809)",
				"President Thomas Jefferson co-authored the Declaration of Independence and enjoyed archaeology",
				"The 4th president was James Madison (1809-1817)",
				"President James Madison had a pet parrot named Polly",
				"The 5th president was James Monroe (1817-1825)",
				"President James Monroe studied law under Thomas Jefferson",
				"President James Monroe established the country's first foreign policy, called the Monroe Doctrine",
				"The 6th president was John Quincy Adams (1825-1829)",
				"President John Quincy Adams was the first president to live in the White House",
				"The 7th president was Andrew Jackson (1829-1837)",
				"President Andrew Jackson is the only president to be a prisoner of war.",
				"President Andrew Jackson is the founder of the Democratic party",
				"The 8th president was Martin Van Buren (1837-1841)",
				"President Martin Van Buren was the first president to be born in the US",
				"The 9th president was William Henry Harrison (1841)",
				"President William Henry Harrison got sick giving his inauguration speech in the rain and died 31 days later.",
				"William Henry Harrison was president for 31 days.",
				"The 10th president was John Tyler (1841-1845)",
				"President John Tyler is the first president to serve without being elected",
				"The 11th president was James K Polk (1845-1849)",
				"President James Polk extended the US by 1.2 million square miles",
				"The 12th president was Zachary Taylor (1849-1850)",
				"President Zachary Taylor was a war hero in the Mexican-American War.",
				"The 13th president was Millard Fillmore (1850-1853)",
				"The 14th president was Franklink Pierce (1853-1857)",
				"President Franklin Pierce helped start the Civil War",
				"The 15th president was James Buchanan (1857-1861)",
				"President James Buchanan had a pet eagle.",
				"The 16th president was Abraham Lincoln (1861-1865)",
				"President Abraham Lincoln was the tallest president, and in the Wrestling Hall of Fame",
				"The 17th president was Andrew Johnson (1865-1869)",
				"President Andrew Johnson was known for vetoing bills passed by congress.",
				"The 18th president was Ulysses S Grant (1869-1877)",
				"President Ulysses S Grant helped establish the National Park System",
				"The 19th president was Rutherford B Hayes (1877-1881)",
				"The 20th president was James A Garfield (1881)",
				"President James Garfield was the 2nd of 3 presidents to servce in 1881. He was shot 200 days into his term.",
				"The 21st president was Chester Arthur (1881 - 1885).",
				"President Chester Arthur had 80 pairs of pants and had the nickname Elegant Arthur.",
				"The 22nd president was Grover Cleveland (1885-1889)",
				"President Grover Cleveland is the only president to serve nonconsecutive terms",
				"The 23rd president was Benjamin Harrison (1889-1893)",
				"President Benjamin Harrison was the first president to live in the White House with electricity",
				"The 24th president was Grover Cleveland (1893-1897)",
				"The 25th president was William McKinley (1897-1901)",
				"President William McKinley was president through the Spanish-American War",
				"The 26th president was Theodore Roosevelt (1901-1909)",
				"President Theodore Rooseveltwon a Nobel Peace Prize",
				"President Theodore Roosevelt was the first to leave the country while in office.",
				"The 27th president was William Taft (1909-1913)",
				"President William Taft established a federal tax through the 16th amendment",
				"President William Taft was the first president to reign over 48 states",
				"The 28th president was Woodrow Wilson (1913-1921)",
				"President Woodrow Wilson was in office during World War 1.",
				"President Woodrow Wilson won a Nobel Peace Prize for working to form the League of Nations",
				"Presidnet Woodrow Wilson is on the $100,000 bill.",
				"The 29th president was Warren G. Harding (1921-1923)",
				"President Warren Harding had size 19 feet.",
				"The 30th president was Calvin Coolidge (1923-1929)",
				"President Coolidge signed the Indian Citizenship Act, which gave full U.S. citizenship rights to all Native Americans",
				"The 31st president was Herbert Hoover (1929-1933)",
				"President Herbert Hoover made The Star-Spangled Banner the national anthem of the United States",
				"President Herbert Hoover was the first president to have a phone at his desk.",
				"President Herbert Hoover donated all of his salary to charity",
				"The 32nd president was Franklin D. Roosevelt (1933-1945)",
				"President Franklin D Roosevelt brought America out of the Great Depression",
				"The 33rd president was Harry S Truman (1945-1953)",
				"President Truman dropped the atomic bombs on Japan, initiated the Marshall Plan and the Truman Doctrine, and embarked on the Korean War",
				"The 34th president was Dwight D. Eisenhower (1953-1961)",
				"President Eisenhower established the current Interstate Highway System and helped to negotiate an end to the Korean War",
				"The 35th president was John F. Kennedy (1961-1963)",
				"President Kennedy is credited for starting the Peace Corps",
				"The 36th president was Lyndon B. Johnson (1963-1969)",
				"The 37th president was Richard Nixon (1969-1974)",
				"President Nixon was the only president to resign",
				"The 38th president was Gerald Ford (1974-1977)",
				"President Gerald Ford was the only man to serve without being elected as either President or Vice President",
				"The 39th president was Jimmy Carter (1977-1981)",
				"The Department of Energy and the Department of Education were created under President Carter",
				"The 40th president was Ronald Reagan (1981-1989)",
				"The 41st president was George Bush (1989-1993)",
				"President George HW Bush was the third American president to be knighted by the Queen",
				"The 42nd president was Bill Clinton (1993-2001)",
				"President Clinton is the second of three presidents to be impeached.",
				"President Bill Clinton was the first to send an email as President.",
				"The 43rd president was George W. Bush (2001-2009)",
				"President George W Bush was office during 9/11 and decided to lead the U.S. into Afghanistan and Iraq",
				"The 44th president was Barack Obama (2009-2017)",
				"President Obama was the first African American president",
				"The 45th president was Donald Trump (2017-2020)",
				"The 46th president was Joe Biden (2020-present)",
				"The oldest-ever person to be elected president is Joe Biden who was 73 on inauguration day",
				"Abraham Lincoln was the first to be born outside the original 13 colonies. He was born in Kentucky.",
				"President Jimmy Carter has been retired for 42 years",
				"Andrew Johnson was the 17th president and the first to be impeached.",
				"James Garfield was the 20th president and first to be left-handed",
			],
			jokes: [
				"I want to be a race car passenger. Just a guy who bugs the driver.",
				"Dogs are forever in the pushup position.",
				"My fake plants died because I did not pretend to water them.",
				"I went to a doctor, all he did was suck blood from my neck. Don't go see doctor Acula.",
				"They say the recipe for Sprite is lemon and lime, but I tried to make it at home. There's more to it than that.",
				"A severed foot is the ultimate stocking stuffer.",
				"I would like it if four people did a cartwheel all at once... so I can make a cart.",
				"I wanted to buy a candle holder, but the store didn't have one. So I got a cake.",
				"I gotta idea for sweat shops... air conditioning! Problem solved.",
				"That would be cool if you lived with a monster... you would never get hiccups!",
				"A fly was very close to being called a 'land' because that's what it does half the time.",
				"A burrito is a sleeping bag for ground beef!",
				"If you're a fish, and you want to become a fish stick, you have to have very good posture.",
				"I bet if you know morse code, a tap dancer drives you crazy.",
				"I'm an ice sculptor. Last night I made a cube.",
				"I'm against picketing, but I don't know how to show it.",
				"I would like to go fishing and catch a fish stick. That would be convenient.",
				"I got an ant farm. They didn't grow anything!",
				"Wearing a turtleneck is like being strangled by a really weak guy... all day.",
				"I haven't slept for 10 days... because that would be too long.",
				"Rice is great if you want to eat 2,000 of something.",
				"A duck's opinion of me is very much influenced over whether or not I have bread.",
				"Every book is a children's book if the kid can read.",
				"I'm afraid for the calendar. Its days are numbered.",
				"Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
				"What do you call a fish wearing a bowtie?Sofishticated.",
				"Dear Math, grow up and solve your own problems.",
				"What did the janitor say when he jumped out of the closet? Supplies!",
				"I only know 25 letters of the alphabet. I don't know y.",
				"Why don't eggs tell jokes? They'd crack each other up.",
				"Why couldn't the bicycle stand up by itself? It was two tired.",
				"Why can't a nose be 12 inches long? Because then it would be a foot.",
				"Shout out to my fingers. I can count on all of them.",
				"I used to play piano by ear. Now I use my hands.",
				"I once got fired from a canned juice company. Apparently I couldn't concentrate.",
				"My dad farted in an elevator, it was wrong on so many levels",
				"How do you throw a space party? You planet",
				"What do you call an alligator in a vest? An investigator",
				"What do you call a super articulate dinosaur? A Thesaurus",
				"Why couldn’t the pony sing in the choir? He was a little horse.",
				"Broken pencils are pointless.",
				"I got a job at a bakery, because I knead dough.",
				"Why do bulls make terrible salesmen? They charge too much.",
				"A book just fell on my head. I only have myshelf to blame.",
				"Where do T-rexes shop? At dino stores.",
				"What’s a cat’s favorite type of Mexican food? Purritos.",
				"What do you call a duck that loves to make jokes? A wise-quacker.",
				"What do dentists call their x-rays? Tooth pics!",
				"What did one ocean say to the other ocean? Nothing, it just waved.",
				"Did you hear about the fire at at the circus? It was in tents!",
				"Why do ducks have feathers? To cover their butt quacks!",
				"Why did the bullet lose it's job? He got fired.",
				"How do you measure a snake? In inches - They don't have feet.",
				"What do you get from a pampered cow? Spoiled milk.",
				"I tried to win a suntanning competition but all I got was bronze.",
				"What do you call a cow with a twitch? Beef jerky.",
				"What did the tie say to the hat? You go ahead, I'll hang around.",
				"I started a job as a tailor last week. It's been sew sew.",
				"What kind of shoes does a spy wear? Sneakers.",
				"What do you call a fake noodle? An impasta.",
				"Where do snowmen keep their savings? A snowbank.",
				"What does a grape do when it's stepped on? Let out a little wine.",
				"Why don't skeletons fight each other? They don't have the guts.",
				"How do farmers mend their pants? With cabbage patches.",
				"To the guy who invented zero, thanks for nothing.",
				"Geology rocks!",
				"Never trust an atom, they make up everything!",
				"Long fairy tales have a tendency to dragon.",
				"What washes up on tiny beaches? Microwaves.",
				"German sausage jokes are just the wurst.",
				"I bought a boat because it was for sail.",
				"What did syrup say to the waffle? I love you a waffle lot!",
				"I'm no cheetah, you're lion!",
				"What did the buffalo say to his son? Bison.",
				"I'm not superstitious, but I'm a little stitious",
				"The older you get, the better you get, unless you're a banana.",
				"I never feel more alone than when I’m trying to put sunscreen on my back.",
				"What do you call an ant who fights crime? A vigilANTe!",
				"Whats the smartest insect? A spelling bee!",
				"What does a storm cloud wear under his raincoat? Thunderwear.",
				"What did the lava say to his girlfriend? 'I lava you!'",
				"What do you call two bananas on the floor? Slippers.",
				"Why did the chicken cross the playground? To get to the other slide.",
				"Why did the chicken cross the road? Just beak-cause he could.",
				"Why did the chicken cross the road? It thought it was an egg-cellent idea.",
				"Why did the cow cross the road? To get to the udder side.",
				"Why did the dog cross the road? To get out of the barking lot.",
				"Where do polar bears vote? The North Poll",
				"What has 8 legs, 8 arms, and 8 eyes? 8 pirates.",
				"What room does a ghost not need? A living room.",
				"How do you stop an astronaut baby from crying? You rocket.",
				"How do billboards talk? Sign language.",
				"What kind of music do mummies listen to? Wrap music.",
				"Why was the broom late to school? It over-swept!",
				"What does a triceratops sit on? On its tricera-bottom.",
				"What do you call a sheep with no legs? A cloud.",
				"Where do hamburgers and hot dogs go dancing? A meatball.",
			],
			language: [
				"The only English word that ends with ‘mt’ is Dreamt.",
				"Sign language has tongue twisters.",
				"The dot over the small letter 'i' is called a tittle.",
				"The word Earth is at least 1,000 years old.",
				"A single strand of Spaghetti is called a “Spaghetto”.",
				"The flashes of colored light you see when you rub your eyes are called “phosphenes”.",
				"To leave a party without telling anyone is called a “French Exit”. In French, it is called “partir à l’anglaise” - to leave like the English.",
				"No word in the dictionary rhymes with the word orange.",
				"No word in the English language rhymes with month.",
				"Every odd number has an 'e' in it.",
			],
			media: [
				"Minnie the Mouse’s first name is not Minnie - it's Minerva.",
				"Snow White was the first Disney Princess",
				"In 1897 the very first comic was The Yellow Kid in McFadden's Flats.",
				"In June of 1939, Action Comics (DC Comics) introduced Superman.",
				"In 70’s DC Comics published a comic book where Superman fights Muhammad Ali and Superman lost.",
				"It takes 40 weeks to animate a single episode of Daniel Tiger's Neighborhood",
				"Daniel Tiger is voiced by an actual child.",
				"Shrek was originally red-nosed, had no teeth, and lived in a dump.",
				"Scar from The Lion King was supposed to be a baboon.",
				"The Flintstones was the most profitable network cartoon franchise for 30 years",
				"Speedy Gonzales has a cousin called Slowpoke Rodriguez that appeared in only two cartoons.",
				"Walt Disney personally hated the Goofy character and found its cartoons to be stupid.",
				"Superman was originally incapable of flying in the 1940s",
				"The first ever known use of the word ‘cartoon’ for an animation was used in October 1916.",
				"Donald Duck’s birthday is officially recognized as June 9, 1934",
				"Originally Naruto was originally supposed to be a chef",
				"Spirited Away was the first anime to ever win an Academy Award",
				"All the Saiyans in Dragon Ball Z are named after vegetables",
				"Sonic the Hedgehog Was Heavily Inspired by Dragon Ball Z",
				"Goku Only Killed Two People Throughout the Series",
				"Goku and Frieza’s First Fight Was the Longest in Anime History",
				"There are no female Super Saiyans",
				"The famous Dragon Ball Z line over 9000! was supposed to be over 8000!",
				"Piccolo, the master of Gohan, is only four years older than Gohan.",
				"Dragon Ball Z‘s Planet Vegeta used to be called Planet Plant",
				"Krillen is a year older than Goku",
				"Goten was originally brought in with the intention of replacing Goku as the main character.",
				"The six dots on Krillin’s forehead are from incense burns from his time training to be a monk at Orin Temple.",
				"Did you know there were 187 fights from Dragon Ball to the end of Dragon Ball Z?",
				"Dragon Ball Z's Goku is close to 50 years old.",
				"Broly's power level was 10,000 at the time he was born.",
				"Planet Namek, home of Kami, King Piccolo and Piccolo Jr, only had about 100 inhabitants.",
				"Goku's full name is Son Goku",
				"Rhydon is the 1st Pokémon ever created.",
				"Pikachu wasn’t Pokémon’s original mascot",
				"Pikachu and Meowth have opposite Pokédex numbers",
				"Pikachu was designed after a squirrel",
				"Slowbro has a chance of devolving",
				"The creator of Pokémon was inspired by insect-catching",
				"There are Pokémon manhole covers in Japan",
				"Shredder from the Ninja Turles was based on a cheese grater",
				"The Ninja Turles originally used a cow head for space travel",
				"Lilo and Stitch was originally supposed to take place in Kansas",
				"Lilo and Stitch was originally created for a children's book",
				"Stitch is also known as Experiment 626",
				"Stitch was created to cause chaos across the galaxy",
				"Stitch is about 3 feet taall",
				"Stitch was originally supposed to be more green",
				"Stitch is bulletproof, fireproof, and can think faster than a computer",
				"Stitch can see in the dark and move objects 3,000 times his size",
				"The pads on Stitch's hands and feet are sticky so he can walk on almost any surface",
				"Stitch cannot float or swim",
				"Cookie Monster's real name is Sid.",
				"The longest running anime is more than 7500 episodes",
				"Sally the Witch is the first magical girl anime",
				"Rainbow Days manga has over 3 million copies",
		],
			nature: [
				"Seventy-one percent of the surface of the Earth is covered by water.",
				"There are more microorganisms in one teaspoon of soil than there are people on earth.",
				"The Amazon rain forest produces half the world’s oxygen supply.",
				"A sunflower is not just one flower. It's 1,000 – 2,000 individual flowers, held together on a single stalk.",
				"At over 2,000 kilometers long, The Great Barrier Reef is the largest living structure on Earth.",
				"It's illegal to own just one guinea pig in Switzerland because they get lonely.",
				"Bamboo can grow up to 35 inches in a day.",
				"Oak trees cannot produce acorns if they are under 50 years of age.",
				"The largest living structure on the planet is the Great Barrier Reef.",
				"Lightning hits oak trees more than any other type of tree.",
				"About 85% of all plant life on the planet is in the ocean.",
				"If it is raining and the birds are still loud outside, the rain is going to continue for a long time (8-10+ hours).",
				"A 2500 square foot lawn produces enough oxygen for a four-person family.",
				"Over 70,000 plant species are medicinal.",
				"Out of 1750 cacti species, 1749 are only found in America.",
				"The Alnwick Garden in England is full of venomous plants.",
				"68% of plant species are endangered.",
				"90% of the food that humans consume comes from 30 plants.",
				"Rubber can only be acquired from 6-year old trees.",
				"Good landscaping can increase the value of a house by up to 20%.",
				"Herbs come strictly from the leaves of a plant.",
				"Plants have the ability to recognize their siblings.",
				"The smell of freshly cut grass is the grass screaming in distress.",
				"There's a wild fig tree in South Africa with roots that go 400 feet deep.",
				"Swamps cover one-fifth of Florida.",
				"There are about 2 million US farms.",
			],
			nerd: [
				"A million seconds is 12 days. A billion seconds is 31 years.",
				"Every 60 seconds in Africa, a minute passes.",
				"In a room of just 23 people, there’s a 50% chance that two people have the same birthday. The probability of two people out of 70 having the same birthday is 99.9%.",
				"There are 80,658,175,170,943,878,571,660,636,856,403,766,975,289,505,440,883,277,824,000,000,000,000 ways to arrange a pack of cards. So, if you shuffle a pack of cards yourself, you are likely to have a deck never seen before in the history of the universe.",
				"There are 31,557,600 seconds in a year.",
			],
			riddles: [
				"Name three consectutive days without naming any of the seven days of the week.",
				"What's at the end of the rainbow?", 
				"Two people were playing chess. They both won. How is this possible?",
				"What word is always spelled wrong?",
				"What invention lets you look right through a wall?",
				"You can hold me in your left hand, but not your right. What am I?",
				"You go at red and stop at green. What am I?", 
				"Easy to lift, but hard to throw. What am I?", 
				"What has a bottom at the top?",
				"What tastes better than it smells?", 
				"What becomes shorter when you add two letters to it?",
				"What can run but not walk?", 
				"What 2 things can you never eat for breakfast?",
				"How do you fix a cracked pumpkin?", 
				"What's yours but mostly used by others", 
				"What word begins with E and ends with E, but only has one letter?", 
				"What goes up but never comes back down?", 
				"What can you break, even if you never pick it up or touch it?", 
				"What kind of lion never roars?", 
				"What has a bottom at the top?", 
			],
			science: [
				"Your funny bone is a nerve.",
				"The continental plates move at the same rate that fingernails grow.",
				"There are 7 different types of twins.",
				"X-rays can’t detect real diamonds.",
				"A candle’s flame is hot and blue in zero gravity.",
				"Water boils at 100 degrees Celcius",
				"There are 7 colors in a rainbow",
				"Plants absorb carbon dioxide from the atmosphere",
				"Water freezes at 32 degrees farenheit",
				"The first element in the periodic table is hydrogen",
				"There are 118 elements in the periodic table",
				"An antibiotic is a medication that fights bacteria but not a virus",
				"Air pressure can be measured using a barometer",
				"Meteorology is the study of weather",
				"Dead skin cells are a main ingredient in household dust",
				"Your nose gets warmer when you lie",
				"Clouds look white because they are reflecting sunlight from above them.",
				"An herb is specifically from plant leaves. A spice is from the seed, bark or root.",
				"You are always looking at your nose, your brain just chooses to ignore it.",
				"Human thigh bones are stronger than concrete.",
				"A flipped coin is more likely to land on the side it started on.",
				"Urine was used as a mouthwash by ancient Romans.",
				"The most successful pirate in history was a woman named Ching Shih.",
				"Your heart is about the same size as your fist.",
				"Your skin is the largest body organ.",
				"There are a billion bacteria in your mouth at any time.",
				"Women's hearts beat faster than men's.",
				"Human blood is as salty as the ocean.",
				"Eyelashes can live for about 150 days before calling out.",
				"You fart on average about 14 times a day.",
				"Each fart leaves your body at 7 mph.",
				"Every minute, your entire blood passes through your heart.",
				"Your brain is more active when you're asleep than when you're awake.",
				"Human teeth are just as strong as shark teeth.",
				"Earwax is actually a type of sweat!",
				"Your eyes blink around 20 times a minute.",
				"Every minute you shed over 30,000 dead skin cells.",
				"On average you fart enough in one day to fill a party balloon.",
				"Children have more taste buds than adults.",
				"We pee enough every month to fill a bath!",
				"Our average body temperature declines as we age.",
				"About 75% of your brain is made of water.",
				"Your heart beats 115,000 times a day.",
				"The human body is made up of about 37 trillion cells.",
				"The human eye has about 2 million working parts.",
				"Humans are born with about 300 bones. They fuse together to form 206 by the time you're an adult.",
				"The human brain will triple its size in the first year",
				"Women's hearts beat faster than men's",
				"Apples float on water.",
				"A bolt of lightning is five times hotter than the sun.",
				"Humans share 50% of their DNA with bananas.",
				"An adult brain weighs three pounds.",
				"The chance of your fingerprint being the same as someone else’s fingerprint is 1 in 64 billion.",
				"If you eat too many carrots your skin will turn orange!",
				"A pearl can be dissolved by vinegar.",
				"Music helps plants grow faster.",
				"Water freezes faster when it’s warm, not cold!",
				"A cloud can weigh over one million pounds.",
				"It takes the human body about 12 hours to digest food after it's been eaten.",
				"If you hold in your farts long enough, the gas can be re-absorbed and come out of your mouth.",
				"Human children don't get kneecap bones until they're around three years old.",
				"There are more trees on earth than there are stars in the galaxy.",
				"Humans share 60% of their DNA with fruit flies.",
				"The smallest bone in the body, inside the ear, is about the size of a grain of rice.",
				"The only thing that can scratch a diamond is a diamond.",
				"There is more water in the atmosphere than in all of our rivers combined.",
				"You can use a pine cone to predict the weather.",
				"You can start a fire with ice.",
				"A fire will burn faster moving uphill than downhill.",
				"The average time it takes for plastic to decompose is 450 years. Glass takes 4,000 years!",
				"People don't sneeze in their sleep.",
				"We cut down around 27,000 trees every day to make toilet paper!",
				"Powerful earthquakes can make the Earth spin faster.",
				"97% of water on the planet is salty and not usable. 2% is frozen.",
				"The oldest living tree in the world is in California, and is around 4,843 years old.",
				"The tallest tree in the world is around 379 feet high.",
				"There are 2,000 thunderstorms on Earth every minute.",
				"The wind is silent until it blows against something.",
				"There are ice caves in Iceland that have hot springs.",
				"Rain contains vitamin B12.",
				"A hurricane releases enough energy in one second to equal that of 10 atomic bombs.",
				"You shed over 30,000 dead skin cells every minute.",
				"You can't breathe and swallow at the same time.",
				"About half of the bones in your body are in your hands and feet.",
				"An adult brain weighs three pounds.",
				"Chalk is made up of fossils.",
				"The acid in your stomach can dissolve steel.",
				"Plankton, seaweed, and other ocean organisms create over half the world’s oxygen.",
				"Boys have fewer taste buds than girls.",
				"Photosynthesis is a process that helps plants make their food.",
			],
			south: [
				"The world's largest drive-in restaurant is in Georgia.",
				"South Carolina produces more peaches than Georgia.",
				"There's a UFO Welcome Center in Bowman, South Carolina",
			],
			space: [
				"Jupiter is the largest planet in our solar system",
				"The sun is the closest star to earth",
				"Mercury is the planet closest to the sun",
				"Jupiter is the largest planet in our solar system. It is over 300 times larger than Earth!",
				"3 planets in our solar system are smaller than earth. Mars, Mercury, and Venus",
				"The Earth travels around the sun at 67,000 miles per hour!",
				"The sky was divided up into 88 different constellations in 1922.",
				"Orion is one of the most visible constellations.",
				"The largest constellation by area is Hydra which is 3.16% of the sky.",
				"Twenty two different constellation names start with the letter C.",
				"The length of Earth's day is increasing by about 1.7 milliseconds every century.",
				"There are more trees on Earth than stars in the Milky Way.",
				"Uranus used to be named George.",
				"A teaspoon of a neutron star weighs over a trillion kilograms.",
				"One light-year is about 9 trillion kilometers (6 trillion miles).",
				"Jupiter is the fastest spinning planet in the solar system.",
				"The sun is about 10,000 degrees Fahrenheit.",
				"Venus is the hottest planet in the solar system, at over 450 degrees Celcius.",
				"It would take 70,000 years to reach the sun on our fastest spaceship.",
				"The sunset on Mars appears blue.",
				"1 million Earths could fit inside the Sun!",
				"The top speed of a rain drop is around 18 mph.",
				"Snowflakes can take an hour to fall from a cloud to the ground.",
				"Venus spins backwards.",
				"On Neptune, the wind blows over 1,000 miles per hour.",
				"A suction cup will not work in outer space.",
				"A group of stars that forms a picture is called a constellation",
				"It rains diamonds on Saturn and Jupiter.",
			],
			sports: [
				"Soccer balls were once used for playing basketball.",
				"The fastest recorded Major League game only lasted for 51 minutes.",
				"The longest MLB game in terms of time lasted for 8 hours and 6 minutes.",
				"Minor League baseball players make no salary.",
				"The recorded speed of the fastest baseball pitch ever thrown is 105.1 mph",
				"A Major League baseball only has a life span of 5-7 pitches.",
				"We can trace the first baseball cap to be made of straw.",
				"The Cincinnati Red Stockings were the first professional baseball team",
				"The Olympics used to give medals for art, not just sports.",

			],
			technology: [
				"Google bought Android in 2005 for $50 million",
				"Originally, Android was developed as an operating system for digital cameras",
				"Android captures 72% of total smart phone market whereas IOS captures 18% market share.",
				"Android’s Google Store has more than 48 billion apps installed in it",
				"The iPhone was not the first smartphone.",
				"In 1983, the very first iPhone was conceived.",
				"The i in iphone stands for 'internet'.",
				"In iPhone ads, it's always 9:42 a.m.",
				"The iPhone's processors are made by Samsung.",
			],
			tennessee: [
				"Tennesse's nickname is The Volunteer State",
				"Tennesse got statehood in 1796. The 16th state.",
				"The capital of Tennesse is Nashville.",
				"The Tennessee state bird is the mockingbird",
				"The Tennessee state flower is the iris",
				"Almost half of Tennessee is farmland!",
				"Tennessee is bordered by 8 states.",
				"Cotton candy was created in 1904 in Tennessee.",
				"Tennessee has 10,000 caves and caverns.",
				"Great Smokey Mountains National Park is the most visited national park in the U.S.",
				"Tennessee is the same size as Cuba",
				"The original inhabitants of Tennessee were the Chickasaw and Cherokee.",
				"The Tennessee state mammal is the raccoon.",
				"The Tennessee state beverage is milk.",
				"The Tennessee state fruit is the tomoato",
				"Three US presidents were from Tennessee.",
				"The Tennesee state tree is the Tulip Tree",
				"Bristol, TN is known at the Birthplace of Country Music",
				"When Tennessee became a state, the total population was 77,000",
				"The Memphis Cotton Exchange handles one third of the entire US cotton crop.",
				"Nashville, TN is known as Music City and is the country music capital of the world.",
				"Tennessee has 10 state songs",
				"The area around Clarksville was first surveyed by Thomas Hutchins in 1768",
				"All of Tennessee was once Washington County, North Carolina",
				"Clarksville was settled in part by soldiers that served under George Washington during the American Revolutionary War",
				"Soldiers from Fort Campbell have been deployed in every military campaign since World War 1",
				"In 1784, John Armstrong filed to create the town of Clarksville, named after General George Clark",
				"When Clarksville was founded, the surrounding area was named Tennessee County.",
				"By 1819, Clarksville had 22 stores including a bakery and silversmith.",
				"In 1820, steamboats allowed Clarksville to trade with other cities, like New Orleans and Pittsburg.",
				"Railroad service came to Clarksville in 1859, between Memphis and Louisville",
				"At the start of the Civil War, Clarksville population was 20,000 people.",
				"In 1878, a fire destroyed 15 acres of downtown clarksville.",
				"Since 1980, the population of Clarksville has more than doubled.",
				"Clarksville is one of the fastest growing large cities in Tennessee and expected to pass Chattanooga",
				"Clarksville is on the northwest edge of the Highland Rim",
				"The first female senator was from Tennesee.",
			],
			tips: [
				"If your bathroom mirrors fog up all the time after a hot shower, rub a cucumber slice along the mirror. It will eliminate the mist and provide a soothing, spa-like fragrance.",
				"The more you say, the more you are responsible for.",
				"Remember to turn your phone ringer back on. Someone you love may be calling.",
				"Go outside in the morning to get natural light. It sets your circadian rhythm for the day. You can combine this practice with a short jog, bike ride, or walk. Lateral eye movement caused by self-propelled motion is shown to reduce stress.",
				"When you don't have all the facts, try to give people the most generous reason you can for their behavior. Annoyingly slow driver? Maybe it's a mom with a birthday cake in the back. This mindset will gradually make you less reactive, more compassionate, and more forgiving of your bad days.",
				"Don't try to be the man your father would want you to be. Be the man you'd like your son to be.",
				"Avoid being the bearer of bad news.",
				"Inhale twice, exhale once. This will help you intake some more oxygen.",
				"Try to get your work done in the morning. The mind clutters over time.",
				"Divide the day into quarters. Instead of saying “I'll do it tomorrow”, say “I'll do it next quarter”.",
				"Defocus your eyes and look out the window. Your brain will release stress-relieving chemicals.",
				"If your boss promises you something, ask them to put it in writing.",
				"Money can be exchanged for goods or services.",
				"Sleep more than you study, study more than you party, and party hard.",
				"Honest people are bad liars.",
				"Unmotivated to exercise? Think about your favorite superheroes/characters",
				"It is important to know when to stop arguing with people, and simply let them be wrong.",
				"Pay attention when people talk. Face them and make relaxed eye contact. They will appreciate you listening.",
				"Be amused. There are few things in life to take seriously.",
				"Smile. Not only will you seem more charismatic, but your body will release chemicals that make you happy.",
				"Under-promise, but over-deliver.",
				"Practice positive self-talk. You will manifest what you say, believe it or not.",
				"Thank people by name. It will impact them much more.",
				"Fix your posture.",
				"It’s a magical world... Let’s go exploring!",
				"After accomplishing a goal, look around to see whether you lost something or someone in the process.",
				"If you are in a bad mood, clean your house. Reducing visual noise and releasing energy is an easy way to reduce stress.",
			],
			misc: [
				"Around 30,000 rubber ducks were lost at sea in 1992.",
				"A park ranger, Roy Sullivan, was once hit by lightning 7 times.",
				"You can’t hum while holding your nose.",
				"You are more likely to have a weird or scary dream when sleeping on your stomach.",
				"It takes a drop of water 90 days to travel the entire Mississippi River",
				"All British armored vehicles have the equipment needed to make tea.",
				"The Queen of England has two birthdays.",
				"You will get cell phone service on the top of Mount Everest.",
				"It is impossible to lick your own elbow.",
				"One pencil can draw a line for 35 miles.",
				"The unique crayon smell comes from beef fat.",
				"Not once in the Humpty Dumpty nursery rhyme does it mention that he's an egg.",
				"California has more people than all of Canada.",
				"In the U.S., there is an official rock, paper, scissors league.",
				"A violin is made from over 70 pieces of wood.",
				"Stores used to sell mail-order houses.",
				"New homes are 30 percent larger than 40 years ago.",
				"46 per cent of people press the snooze button more than once when waking up.",
				"A pentagon is a shape with 5 sides",
				"Red, blue, and yellow are the three primary colors",
				"12% of people dream entirely in black and white",
				"The longest someone has gone without sleep is 11 days, 25 minutes.",
				"A dime has 118 ridges on its edge.",
				"On average, a secretary will use their left hand for 56% of what they type.",
				"A french pig was executed for killing a child.",
			]
		},
	},


	// executes on start 
	start: function() {
		Log.info("Starting module: " + this.name);

		this.lastFactIndex = -1;

		// update timer
		var self = this;
		setInterval(function() {
			self.updateDom(self.config.fadeSpeed * 1000);
		}, this.config.updateInterval * 1000);
	},

	// generate fact
	randomIndex: function(facts) {
		if (facts.length === 1) {
			return 0;
		}

		var generate = function() {
			return Math.floor(Math.random() * facts.length);
		};

		var factIndex = generate();

		while (factIndex === this.lastFactIndex) {
			factIndex = generate();
		}

		this.lastFactIndex = factIndex;

		return factIndex;
	},

	// create an array of facts
	factArray: function() {
		if (this.config.category == 'random') {
			return this.config.facts[Object.keys(this.config.facts)[Math.floor(Math.random() * Object.keys(this.config.facts).length)]];
		} else {
			return this.config.facts[this.config.category];
		}
	},

    	// return a fact from array of facts
	randomFact: function() {
		var facts = this.factArray();
		var index = this.randomIndex(facts);
		return facts[index];
	},

	// override getDom to display fact
	getDom: function() {
		var factText = this.randomFact();

		var text = factText;

		var wrapper = document.createElement("div");

		var fact = document.createElement("div");
		fact.className = "bright medium light facts";
		fact.style.textAlign = 'center';
		fact.style.margin = '0 auto';
		fact.style.maxWidth = '95%';
		fact.innerHTML = text;

		wrapper.appendChild(fact);

		return wrapper;
	}

});
